# Generated by Django 4.1.9 on 2023-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('sender', models.CharField(max_length=42)),
                ('recipient', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
